"""
Django settings for taskmanager project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from taskmanager import VERSION

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Everything that differs between a laptop and a server comes from a TASKMANAGER_* environment
# variable and has a default that works locally, so `manage.py migrate` + `manage.py runserver`
# need no configuration. README.md lists every variable.
def env(name, default):
    return os.environ.get("TASKMANAGER_" + name, default)


def env_int(name, default):
    value = int(env(name, default))
    if value < 1:
        raise ValueError(f"TASKMANAGER_{name} must be a positive integer")
    return value


def env_bool(name, default):
    return str(env(name, default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default):
    raw = env(name, None)
    if raw is None:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


# The SQLite database lives here: back up this directory and you have backed up the service.
DATA_DIR = Path(env("DATA_DIR", BASE_DIR / "data")).resolve()
DATA_DIR.mkdir(parents=True, exist_ok=True)  # SQLite will not create the directory itself


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", "django-insecure--%ibp*%hl=7noua-!%tq($d95wjrbsl4jt3-5!3)b)^x!j38gl")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", "false")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["*"])


# Application definition

INSTALLED_APPS = [
    "jazzmin",  # admin theme; must come before django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "core",
    "accounts",
    "tasks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves the admin's static files itself, so the admin looks right without nginx or
    # `runserver --insecure`.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "taskmanager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "taskmanager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "db.sqlite3",
        # WAL lets readers and the single writer work at the same time; the busy timeout makes
        # concurrent writes wait for the lock instead of failing.
        "OPTIONS": {
            "timeout": 5,
            "transaction_mode": "IMMEDIATE",
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
        },
    }
}


# Django recommends a custom user model from the first migration, even when it adds nothing
# yet, because switching later is painful (accounts.models.User).
AUTH_USER_MODEL = "accounts.User"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# WhiteNoise finds the admin's files through the staticfiles finders, so no collectstatic step.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Task manager settings (README.md explains each one)

TASKMANAGER_PAGE_SIZE = env_int("PAGE_SIZE", 20)
TASKMANAGER_MAX_PAGE_SIZE = env_int("MAX_PAGE_SIZE", 100)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.DefaultPagination",
    # JSON only: it keeps every response, including errors, in one format.
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "EXCEPTION_HANDLER": "core.errors.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# JWT (djangorestframework-simplejwt): POST /auth/token/ issues an access + refresh pair.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env_int("ACCESS_TOKEN_MINUTES", 60)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env_int("REFRESH_TOKEN_DAYS", 7)),
}

# OpenAPI 3 schema at /openapi.json, Swagger UI at /docs/, ReDoc at /redoc/ (drf-spectacular).
SPECTACULAR_SETTINGS = {
    "TITLE": "Task manager API",
    "DESCRIPTION": (
        "Create tasks, assign them to other users, mark them done and discuss them in "
        "comments. Sign in with a JWT: register at `/auth/register/`, get a token at "
        "`/auth/token/`, then press Authorize and paste the access token. Errors are JSON "
        "with a human `detail` and a machine-readable `code`."
    ),
    "VERSION": VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True, "displayRequestDuration": True},
}

# The admin theme (django-jazzmin). Everything here is cosmetic; /admin/ works without it.
JAZZMIN_SETTINGS = {
    "site_title": "Task manager",
    "site_header": "Task manager",
    "site_brand": "Task manager",
    "welcome_sign": "Task manager admin",
    "copyright": "Task manager",
    "search_model": ["tasks.Task", "accounts.User"],
    "order_with_respect_to": ["tasks", "accounts", "auth"],
    "icons": {
        "tasks.Task": "fas fa-tasks",
        "tasks.Comment": "fas fa-comments",
        "accounts.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "topmenu_links": [
        {"name": "API docs", "url": "/docs/", "new_window": True},
    ],
    "show_ui_builder": False,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"plain": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "plain"}},
    "root": {"handlers": ["console"], "level": env("LOG_LEVEL", "INFO").upper()},
}
